### PR TITLE
Update

### PR DESCRIPTION
**Pull request by miyakowilson**
Refactor, update gradle for MD 18,4, fix Library button, dialog to be
resizable(JIRA MAGICDRAW-407),. add auto-complete(JIRA MAGICDRAW-424), add a capability to modify expression using constraint editor(JIRA MAGICDRAW-426), provide an entry field for the name of a constraint (JIRA MAGICDRAW-408), add a menu to edit constraints in the containment tree (JIRA MAGICDRAW-406) and a capability to open dialog by right-clicking a constraint.

### CODE REVIEW

**Comment by miyakowilson** [comment]
Fix a bug introduced by the refactor.

**Comment by miyakowilson** [comment]
Infix is now supporting most of AsciiMath syntax.  Infix does not use antlr (tree) parser anymore.  It uses xml generated by the AsciiMathParser.js to convert the text expression into MagicDraw StringExpression.  The prefix is not modified.

**Comment by miyakowilson** [comment]
- Greek characters with one more variable(alpha_5) is now supported as a constraint parameter.
- Subscripts followed by a number(ie., 890)  or a character (ie., alpha_890, x_1, xy_123, x13ion_i, a_i) is now supported as a constraint parameter.
- Modify only to process when the text expression is changed.
- If the expression is invalid, the dialog shows its AsciiMath expression with (Invalid) appended in red.

**Comment by miyakowilson** [comment]
Here are the jira bugs fixed.
MAGICDRAW-428 - Automatically add () after functions or select operations in the Expression Editor.
MAGICDRAW-426 - Allow for the capability of a user to insert operands or operations inside an expression using the constraint editor.
MAGICDRAW-424 - Auto-completion of operands and operators.
MAGICDRAW-408 - Provide an entry field for the name of a constraint.
MAGICDRAW-407 - Make the Constraint Editor gui resizable.
MAGICDRAW-406 - Add menu to edit constraints in the containment tree

Other modification: 
- If the expression is invalid show in red.
- If the expression did not changed with its md stored expression,  "Expression not changed" message window shows up.
- A variable with _ is considered as a operand.
- The "^" character is a superscript in mathML and considered as power operator.
- A "f" or "g" is allowed with () in the mdk-expression and considered as a operand.  f(x), f(xy), and g(x+a) are valid operands. 
- Prefix is supported as is and md with prefix expression is still supported but must stay as prefix.
- Since infix no longer using the original antler parser rather using AsciiMathParser, no mathematical validation is included.  For example, a expression "a+-*5" is valid in the mdk-expression and stored fine in the md. 
- Libraries can be reloaded.
- Ask a user if the user like the mdk-expression to create a operand that included in the expression but not exist in MD as a constraint parameter (not working for a variable with subscript y_1).
- Removed the Infix and Prefix radio button selection.

**Review by ivan-gomes — APPROVED** [review]

**Pull request merged**
